Stage 2
gambrinus304/market pull request #2
Opened 2018-04-07 23:29 UTC by gambrinus304

Did the job the second week

2018-04-09 08:17 UTC, bluzir requested changes
Добавить ссылки на товары

2018-04-09 08:17 UTC, bluzir commented on django_market/urls.py
> +    path('prod/<int:pk>/', views.ProductDetail.as_view(), name='detail'),
`prod` – плохое название для урлы

`detail` – плохое название для именованного урла

`products` в ссылке на товары, и `products_detail` в именованном

2018-04-09 08:17 UTC, bluzir commented on django_market/urls.py
> +    path('cat/', views.CategoryListView.as_view(), name='categories'),
name = `сategory_list`

2018-04-09 08:17 UTC, bluzir commented on django_market/urls.py
> +    path('cat/', views.CategoryListView.as_view(), name='categories'),
и в пути `category` — сокращения не нужны

2018-04-09 08:17 UTC, bluzir commented on django_market/urls.py
> +    path('catdel/<int:pk>/', views.CategoryDetail.as_view(), name='category'),
name = `category_detail`

2018-04-09 21:23 UTC, gambrinus304 commented
fix bad urls

2018-04-12 09:11 UTC, bluzir approved these changes

2018-04-12 09:11 UTC, merged